language: node_js

compiler: gcc
sudo: false

os:
- linux
#- osx

env:
  global:
    - secure: Jer6INk7ftAkEmrzky9af9nB6MVkLTTjQ90JuD4NchQbmBiIAT80shIRfDEekqSoP8kDcIqdAXoWEVIyF6Un8TPStj8MomVEQSNZ25W9KIh+nx6CGLRdPEUb29QmGFq6MaZ5hDnNhzSCkkT/ljOj8KME5b0zPiwenA30kPYxCc8h3/SUp+Zb8NV2um9z+nkp69naHfX7nXXjGJer8yMFU0h5XpBmRY/vrv2cP6LJg+yaZA6vWbBbmQnxtnNMKrSmjh4+GSDg5ENu3mTtkHNd4aVpk52yXUNTmz0R3W33qd9nem189snWvI0N+v0Ww9hVv+Lo9sxPQS/Hwco+qtjmGRAeFbd6Y92Sgu+OWfNbPM2gQ2dgRpaC4o7/3zJDay85I9gIVVqgKez+DEfpOJcKlvFBuJ8IWCvQS5K45WTaIz6hnv+c7c06G244lzk/fPwD35rT6wug+aV7pGfhQg1nMoYeC7AVhtVWL8SJ6TIdoCOnvuGp4SeTkE4L6XvGZEblF/VDhexmhUjQhXiWMIw4MEx8VFS4wbVS1m4+HZ7xJ6Uz9DuNvg9EvwdSYudpE2QGn7dmzo/E+t5s7eotmQ9l1NEKjN0GAip36NpDNj1/8Ew1fWcijXRmkVbGbx2tm9qY2D62deNS9RNZk4EEy6Ts/egWXhzzokinh8LOXkBqIM4=

node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    
sudo: false

before_install:
- if [ "$TRAVIS_NODE_VERSION" = "0.8" ]; then npm install -g npm@2.7.3; fi;
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CC="gcc-4.8";
    export CXX="g++-4.8";
    export LINK="gcc-4.8";
    export LINKXX="g++-4.8";
  fi
- nvm --version
- node --version
- npm --version
- gcc --version
- g++ --version

before_script:
# figure out if we should publish
- echo $TRAVIS_BRANCH
- echo `git describe --tags --always HEAD`
- PUBLISH_BINARY=false
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` || ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then PUBLISH_BINARY=true; fi;
- echo "Publishing binaries? ->" $PUBLISH_BINARY

install:
- npm install

script:
- npm test
- if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package && node-pre-gyp-github publish --release; fi;

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules